#!/usr/bin/env bash

if [ $# != '1' ]; then
    echo "Expected single argument!";
    echo "Usage: $0 file_name";
    exit 1;
fi

echo "Enter the name of the keypair you want to associate with the instance. This will allow you to access it (although it is discouraged) when it is running";
echo "It is your responsibility to make sure that the keypair you are entering is indeed valid"
read -p "Enter key pair name (enter for nil keypair) " KEY_PAIR_NAME
echo -n $KEY_PAIR_NAME >$1;

exit 0
