#!/usr/bin/env bash

if [ $# != 1 ]
then
    echo "Expected 1 argument!";
    echo "Usage: ";
    echo "$0 filename";
    exit 1;
fi

FILE_NAME="$1"
read -p "Enter bucket name: " BUCKET_NAME

if [ -z "$BUCKET_NAME" ]; then
    BUCKET_NAME="core.matrix.bench-marks"
fi

BUCKET_URL="s3://$BUCKET_NAME"

# Decide whether to create a bucket or not
aws s3 ls $BUCKET_NAME &>/dev/null # don't care bout the output, interested only in status code

if [ $? = "0" ]
then
    while true; do
        read -p "The bucket exists, do you want to overwrite it? (y/n)" res;
        if [ "$res" = 'y' ]
        then
            aws s3 rb $BUCKET_URL --force
            break
        elif [ "$res" = "n" ]
        then
            echo "Not going to create a new bucket, terminating now!";
            exit 0;
        else
            echo "Unregocnized response '$res' !"
        fi
    done
fi

aws s3 mb $BUCKET_URL

echo -n $BUCKET_NAME >$FILE_NAME
